# nixpacks.toml
# Don’t try to auto-detect a single language
skip_detect = true

# Install both back- and front-end dependencies
[phases.install]
cmds = [
  "pip install -r backend/requirements.txt",
  "npm install --prefix frontend/movie-recommendation-ui"
]

# Build the React app
[phases.build]
cmds = [
  "npm run build --prefix frontend/movie-recommendation-ui"
]

# Start your Flask API on the port Nixpacks provides
[start]
cmd = "gunicorn -b 0.0.0.0:${PORT} backend.app:app"
